steps:
  # Step 1: Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voicebot-frontend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/voicebot-frontend:$COMMIT_SHA'
      - '-f'
      - 'frontend/Dockerfile'
      - '.'

  # Step 2: Push the frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/voicebot-frontend:latest'

  # Step 3: Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'voicebot-frontend'
      - '--image=gcr.io/$PROJECT_ID/voicebot-frontend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=VITE_API_BASE_URL=${_BACKEND_URL}'

images:
  - 'gcr.io/$PROJECT_ID/voicebot-frontend:latest'
  - 'gcr.io/$PROJECT_ID/voicebot-frontend:$COMMIT_SHA'

substitutions:
  _BACKEND_URL: 'https://voicebot-backend-xxxxx.a.run.app'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: '1800s'
